### ISSUE TITLE
receiveMultipleMessages test random failure

### ISSUE THREAD

**Issue by i-Alex** [HorizenOfficial/Sidechains-SDK#171]
From user:
building with maven fails (randomly without changing anything) 2/3 times for me on the test receiveMultipleMessages() in WebSocketChannelImplTest.scala. adding a Thread.sleep(50) in WebSocketServerPushEndpoint.scala seems to fix that issue for me.
 my guess is that something else is blocking the send or the server has not completely started as the test relies on sending on the annotation "@onOpen". that would also explain why adding a Thread.sleep fixes the issue aleast on my system. this is what happens when the build fails.

> [main] INFO com.horizen.websocket.WebSocketConnectorImpl - Starting web socket connector...
[main] INFO com.horizen.websocket.DefaultWebSocketReconnectionHandler - onConnectFailure. Reconnecting... (attempt 1) Connection failed.
[main] INFO com.horizen.websocket.DefaultWebSocketReconnectionHandler - onConnectFailure. Reconnecting... (attempt 2) Connection failed.
[main] INFO com.horizen.websocket.DefaultWebSocketReconnectionHandler - onConnectFailure. Reconnecting... (attempt 3) Connection failed.
[main] INFO com.horizen.websocket.WebSocketConnectorImpl - Stopping web socket connector...
Jul 26, 2020 12:55:26 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8999]
Jul 26, 2020 12:55:26 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer-4] Started.
Jul 26, 2020 12:55:26 PM org.glassfish..tyrus.serverServer start
INFO: WebSocket Registered apps: URLs all start with ws://localhost:8999
Jul 26, 2020 12:55:26 PM org.glassfish.tyrus.server.Server start
INFO: WebSocket server started.
[main] INFO com.horizen.websocket.WebSocketConnectorImpl - Starting web socket connector...
[main] INFO com.horizen.websocket.WebSocketConnectorImpl - Web socket connector started.
Jul 26, 2020 12:55:26 PM org.glassfish.tyrus.core.AnnotatedEndpoint onError
INFO: Unhandled exception in endpoint com.horizen.websocket.WebSocketConnectorImpl.
java.lang.IllegalStateException: Text message handler not found. Session: 'TyrusSession{uri=ws://localhost:8999, id='73d201ec-debf-49e5-8f60-6fa89e24d23e', endpointWrapper=TyrusEndpointWrapper{endpointClass=null, endpoint=org.glassfish.tyrus.core.AnnotatedEndpoint@134bc9c1, contextPath='ws://localhost:8999', endpointPath=null, encoders=[CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.NoOpTextCoder, coder=org.glassfish.tyrus.core.coder.NoOpTextCoder@17745f70, type=class java.lang.String}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.NoOpByteBufferCoder, coder=org.glassfish.tyrus.core.coder.NoOpByteBufferCoder@5276c3fa, type=class java.nio.ByteBuffer}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.NoOpByteArrayCoder, coder=org.glassfish.tyrus.core.coder.NoOpByteArrayCoder@2e26c180, type=class [B}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.ToStringEncoder, coder=org.glassfish.tyrus.core.coder.ToStringEncoder@63ee1044, type=class java.lang.Object}], decoders=[CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$BooleanDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$BooleanDecoder@56544c96, type=class java.lang.Boolean}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$ByteDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$ByteDecoder@32593cb5, type=class java.lang.Byte}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$CharacterDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$CharacterDecoder@2aebd1bf, type=class java.lang.Character}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$DoubleDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$DoubleDecoder@39949896, type=class java.lang.Double}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$FloatDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$FloatDecoder@4d5043ce, type=class java.lang.Float}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$IntegerDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$IntegerDecoder@36176245, type=class java.lang.Integer}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$LongDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$LongDecoder@42853b11, type=class java.lang.Long}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.PrimitiveDecoders$ShortDecoder, coder=org.glassfish.tyrus.core.coder.PrimitiveDecoders$ShortDecoder@5fc84bff, type=class java.lang.Short}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.NoOpTextCoder, coder=org.glassfish.tyrus.core.coder.NoOpTextCoder@10493dfb, type=class java.lang.String}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.NoOpByteBufferCoder, coder=org.glassfish.tyrus.core.coder.NoOpByteBufferCoder@1d4160fd, type=class java.nio.ByteBuffer}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.NoOpByteArrayCoder, coder=org.glassfish.tyrus.core.coder.NoOpByteArrayCoder@76779df7, type=class [B}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.ReaderDecoder, coder=org.glassfish.tyrus.core.coder.ReaderDecoder@6bfda775, type=class java.io.Reader}, CoderWrapper{coderClass=class org.glassfish.tyrus.core.coder.InputStreamDecoder, coder=org.glassfish.tyrus.core.coder.InputStreamDecoder@3282f914, type=class java.io.InputStream}]}}'.
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:859)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:192)
        at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:115)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:783)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:724)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:515)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:834)

> [Grizzly(1)] INFO com.horizen.websocket.WebSocketConnectorImpl - Message received from server: Message #2
> [Grizzly(1)] INFO com.horizen.websocket.WebSocketConnectorImpl - Message received from server: Message #3
> [Grizzly(1)] INFO com.horizen.websocket.WebSocketConnectorImpl - Message received from server: Message #4
> [Grizzly(1)] INFO com.horizen.websocket.WebSocketConnectorImpl - Message received from server: Message #5

**Comment by i-Alex** [comment]
Done and merged. Just in-test issue.
