### ISSUE TITLE
Error message when multiple nodes are forging 

### ISSUE THREAD

**Issue by lander86** [HorizenOfficial/Sidechains-SDK#238]
When multiple nodes are setted up to forge new blocks on a sidechain, this error message occurs often in the logs : 

`2021-02-17 14:09:48:992 +0000 [2-Hop-akka.actor.default-dispatcher-28822] ERROR com.horizen.forge.ForgeMessageBuilder - Failed to forge block for 3 epoch 324 slot due:
java.lang.IllegalArgumentException: Try to forge block with incorrect epochAndSlot Epoch: 3, Slot 324 which are equal or less than parent block epochAndSlot: Epoch: 3, Slot 324
        at com.horizen.forge.ForgeMessageBuilder.checkNextEpochAndSlot(ForgeMessageBuilder.scala:113)
        at com.horizen.forge.ForgeMessageBuilder.$anonfun$tryToForgeNextBlock$1(ForgeMessageBuilder.scala:50)
        at scala.util.Try$.apply(Try.scala:213)
        at com.horizen.forge.ForgeMessageBuilder.tryToForgeNextBlock(ForgeMessageBuilder.scala:39)
        at com.horizen.forge.ForgeMessageBuilder.$anonfun$buildForgeMessageForEpochAndSlot$1(ForgeMessageBuilder.scala:31)
        at scorex.core.NodeViewHolder$$anonfun$getCurrentInfo$1.applyOrElse(NodeViewHolder.scala:362)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at com.horizen.SidechainNodeViewHolder.aroundReceive(SidechainNodeViewHolder.scala:23)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2021-02-17 14:09:48:993 +0000 [scala-execution-context-global-903] ERROR com.horizen.forge.Forger - Forging had been failed. Reason: Try to forge block with incorrect epochAndSlot Epoch: 3, Slot 324 which are equal or less than parent block epochAndSlot: Epoch: 3, Slot 324`

This happens when one node forge a block in a certain slot/epoch and another node tries to forge the same block/slot. If this behaviour is normal, probably we should just throw an "INFO" instead of an "ERROR" .

**Comment by i-Alex** [comment]
We need to review the order of checks during forging and update the behavior of logs.
Moreover, we need to do the same for CertificateSubmitter, especially the error message in case certificate was rejected by the MC node.

**Comment by lander86** [comment]
I've spotted something strange in the last sidechain's log : 

`2021-02-18 13:37:44:044 +0000 [2-Hop-akka.actor.default-dispatcher-76274] INFO com.horizen.SidechainState - Block contains successfully verified backward transfer certificate for epoch %d`

It seems that the epoch number is not correctly showed. We could add also this to this issue.
