### ISSUE TITLE
Error with locale

### ISSUE THREAD

**Issue by lander86** [HorizenOfficial/Sidechains-SDK#257]
If the locale on the OS is not set to UTF-8, a node, when started, will throw an INFO : 

>`[INFO ] 2021-05-05 15:45:28:272 +0000 [main] com.horizen.websocket.WebSocketConnectorImpl - Web socket connector started.
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.nio.charset.MalformedInputException: Input length = 1
  at com.horizen.SidechainAppModule.get(SidechainAppModule.scala:66)
  while locating com.horizen.SidechainApp

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at io.horizen.auditapp.AuditApp.main(AuditApp.java:31)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:74)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.TraversableOnce.addString(TraversableOnce.scala:404)
        at scala.collection.TraversableOnce.addString$(TraversableOnce.scala:389)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1431)
        at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:359)
        at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:358)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1431)
        at scala.collection.TraversableOnce.mkString(TraversableOnce.scala:361)
        at scala.collection.TraversableOnce.mkString$(TraversableOnce.scala:361)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1431)
        at com.horizen.SidechainApp.<init>(SidechainApp.scala:281)
        at com.horizen.SidechainAppModule.get(SidechainAppModule.scala:88)
        at com.horizen.SidechainAppModule$$FastClassByGuice$$a3f92c19.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        ... 2 more`

The node will keep working but the API will not start at all (and obviously will not be reachable then). If the log level is set to ERROR or also WARNING you will not notice the error (because is actually thrown as an INFO). The node will get in sync with the sidechain and will partially works without throwing any other error/warning/advice.

**Comment by i-Alex** [comment]
This error occurred because the swagger config file reading was failed during the Node initialization: `Source.fromResource("api/sidechainApi.yaml").getLines.mkString("\n")`.
The charset of "api/sidechainApi.yaml" is UTF-8.

According to this issue we need to specify directly the encoding in the code instead of using the OS one by default.
The OS mentioned above had a POSIX locale by default.
Note: check other places similar to this one.
